### ISSUE TITLE
Pls fix Text

### ISSUE THREAD

**Issue by Moritz-Mi** [simonmeusel/raacma-source#2]
pls fix das text nicht übereinander steht

**Comment by Moritz-Mi** [comment]
Wenn du alles löscht sollte ARGS und BR0 wieder erzeugt werden wie wenn die seite geladen wird.

**Comment by qmnl** [comment]
See #3

**Comment by qmnl** [comment]
Fixed with 9c8e0bf530c1934503f995a641f0f60c1276cda8
